#!/usr/bin/env python3
"""Mochi Squad deterministic setup / verify / repair tool.

This script is intentionally stdlib-only and side-effect-aware. Use --plan first
when running against a real Hermes home.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

SKILL_VERSION = "0.1.0"
CORE_PROFILES = ("mochi-exec", "mochi-review")
OPTIONAL_PROFILES = ("mochi-research",)
PROFILE_TOOLSETS = {
    "mochi-exec": ["file", "terminal", "kanban", "skills"],
    "mochi-review": ["file", "terminal", "kanban", "skills"],
    "mochi-research": ["web", "search", "browser", "file", "kanban", "skills"],
}

TEMPLATE_CONFIG = """# Mochi Squad local runtime config
# Generated by setup.py --install. Edit for your deployment.

kanban:
  db_path: auto

profiles:
  exec: mochi-exec
  review: mochi-review
  # Optional/future worker; not installed by default unless explicitly enabled.
  research: mochi-research

watchers:
  blocked:
    enabled: false
    schedule: "every 5m"
    notify_target: origin
    script: scripts/blocked-watchdog.py

virtual_office:
  enabled: false
  listen_host: 127.0.0.1
  port: 3000
  public_base_url: null
"""


def now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def skill_dir() -> Path:
    return Path(__file__).resolve().parents[1]


def repo_root() -> Path:
    return skill_dir().parents[1]


def default_hermes_home(value: str | None = None) -> Path:
    return Path(value or os.environ.get("HERMES_HOME", os.path.expanduser("~/.hermes"))).expanduser().resolve()


def default_runtime_dir(hermes_home: Path) -> Path:
    return hermes_home / "mochi-squad"


def profile_dir(hermes_home: Path, profile: str) -> Path:
    return hermes_home / "profiles" / profile


def runtime_state_path(runtime_dir: Path) -> Path:
    return runtime_dir / "state.yaml"


def read_json_yaml(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text())
    except json.JSONDecodeError:
        return {"_parse_error": f"{path.name} is expected to be JSON-compatible YAML"}


def write_json_yaml(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n")


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def copy_tree_missing(src: Path, dst: Path) -> bool:
    if dst.exists():
        return False
    ignore = shutil.ignore_patterns("__pycache__", "*.pyc", ".git")
    shutil.copytree(src, dst, ignore=ignore)
    return True


def recommended_profile_config(profile: str) -> str:
    toolsets = PROFILE_TOOLSETS[profile]
    return """# Mochi Squad recommended Hermes profile config
# Generated only for newly-created profiles. Existing profile configs are audited, not overwritten.

skills:
  - mochi-squad

enabled_toolsets:
""" + "".join(f"  - {tool}\n" for tool in toolsets)


def profile_template(profile: str) -> Path:
    return skill_dir() / "templates" / "profiles" / profile / "SOUL.md"


def build_plan(hermes_home: Path, runtime_dir: Path, include_optional: bool = False) -> dict[str, Any]:
    profiles = list(CORE_PROFILES) + (list(OPTIONAL_PROFILES) if include_optional else [])
    actions: list[dict[str, str]] = []
    warnings: list[str] = []

    for directory in (runtime_dir, runtime_dir / "logs", runtime_dir / "cache", runtime_dir / "scripts"):
        if not directory.exists():
            actions.append({"action": "create_dir", "path": str(directory)})

    if not (runtime_dir / "config.yaml").exists():
        actions.append({"action": "create_file", "path": str(runtime_dir / "config.yaml")})
    if not runtime_state_path(runtime_dir).exists():
        actions.append({"action": "create_file", "path": str(runtime_state_path(runtime_dir))})

    watcher_src = skill_dir() / "scripts" / "blocked-watchdog.py"
    watcher_dst = runtime_dir / "scripts" / "blocked-watchdog.py"
    if watcher_src.exists() and not watcher_dst.exists():
        actions.append({"action": "copy_file", "path": str(watcher_dst)})

    for name in profiles:
        pdir = profile_dir(hermes_home, name)
        newly_created = not pdir.exists()
        if newly_created:
            actions.append({"action": "create_profile", "path": str(pdir)})
        soul = pdir / "SOUL.md"
        if newly_created:
            actions.append({"action": "copy_profile_soul", "path": str(soul)})
        elif not soul.exists():
            warnings.append(f"{name}: SOUL.md missing; setup will not create it without explicit profile creation")
        cfg = pdir / "config.yaml"
        if newly_created:
            actions.append({"action": "write_profile_config", "path": str(cfg)})
        elif not cfg.exists():
            warnings.append(f"{name}: config.yaml missing; Hermes may fall back to global/default settings")
        skill_dst = pdir / "skills" / "mochi-squad"
        if not skill_dst.exists():
            actions.append({"action": "install_profile_skill", "path": str(skill_dst)})

    return {
        "action": "plan",
        "hermes_home": str(hermes_home),
        "runtime_dir": str(runtime_dir),
        "core_profiles": list(CORE_PROFILES),
        "optional_profiles_included": include_optional,
        "will_change": actions,
        "warnings": warnings,
        "approval_required": [
            "overwriting existing SOUL.md or profile config.yaml",
            "editing model/provider/toolsets for existing profiles",
            "creating Hermes cron jobs or configuring notification targets",
            "configuring DNS, Cloudflare, reverse proxies, or public URLs",
        ],
    }


def install(hermes_home: Path, runtime_dir: Path, include_optional: bool = False) -> dict[str, Any]:
    plan = build_plan(hermes_home, runtime_dir, include_optional=include_optional)
    changed: list[str] = []
    skipped: list[str] = []
    profile_audit: dict[str, Any] = {}

    runtime_dir.mkdir(parents=True, exist_ok=True)
    for sub in ("logs", "cache", "scripts"):
        d = runtime_dir / sub
        if d.exists():
            skipped.append(f"{sub}/ already exists")
        else:
            d.mkdir(parents=True)
            changed.append(f"created {sub}/")

    cfg = runtime_dir / "config.yaml"
    if cfg.exists():
        skipped.append("config.yaml already exists")
    else:
        cfg.write_text(TEMPLATE_CONFIG)
        changed.append("created config.yaml")

    watcher_src = skill_dir() / "scripts" / "blocked-watchdog.py"
    watcher_dst = runtime_dir / "scripts" / "blocked-watchdog.py"
    watcher_checksum = None
    if watcher_src.exists():
        if watcher_dst.exists():
            skipped.append("scripts/blocked-watchdog.py already exists")
        else:
            shutil.copy2(watcher_src, watcher_dst)
            changed.append("copied scripts/blocked-watchdog.py")
        watcher_checksum = sha256(watcher_dst)

    profiles = list(CORE_PROFILES) + (list(OPTIONAL_PROFILES) if include_optional else [])
    for name in profiles:
        pdir = profile_dir(hermes_home, name)
        existed = pdir.exists()
        pdir.mkdir(parents=True, exist_ok=True)
        if not existed:
            changed.append(f"created profile {name}")
        soul = pdir / "SOUL.md"
        if not existed and profile_template(name).exists():
            shutil.copy2(profile_template(name), soul)
            changed.append(f"copied {name}/SOUL.md")
        elif soul.exists():
            skipped.append(f"{name}/SOUL.md exists")
        else:
            skipped.append(f"{name}/SOUL.md missing; existing profile not modified")

        pcfg = pdir / "config.yaml"
        if not existed:
            pcfg.write_text(recommended_profile_config(name))
            changed.append(f"wrote {name}/config.yaml")
        elif pcfg.exists():
            skipped.append(f"{name}/config.yaml exists")
        else:
            skipped.append(f"{name}/config.yaml missing; existing profile not modified")

        skill_dst = pdir / "skills" / "mochi-squad"
        copied_skill = copy_tree_missing(skill_dir(), skill_dst)
        if copied_skill:
            changed.append(f"installed mochi-squad skill for {name}")
        else:
            skipped.append(f"{name}/skills/mochi-squad exists")

        profile_audit[name] = audit_profile(hermes_home, name)

    state = read_json_yaml(runtime_state_path(runtime_dir))
    state.update({
        "version": SKILL_VERSION,
        "installed": True,
        "installed_at": state.get("installed_at") or now_iso(),
        "last_verified_at": now_iso(),
        "runtime_dir": str(runtime_dir),
        "profiles": profile_audit,
        "scripts": {
            "blocked-watchdog.py": {
                "installed": watcher_dst.exists(),
                "path": str(watcher_dst),
                "sha256": watcher_checksum,
            }
        },
        "blocked_watcher": {
            "cron_installed": False,
            "cron_job_id": None,
            "dedupe_state_path": str(runtime_dir / "blocked-watchdog-state.json"),
            "note": "Use Hermes cron/no_agent to schedule scripts/blocked-watchdog.py; setup does not mutate cron jobs directly.",
        },
        "virtual_office": {"enabled": False, "reason": "deferred"},
    })
    write_json_yaml(runtime_state_path(runtime_dir), state)
    if "created state.yaml" not in changed and runtime_state_path(runtime_dir).exists():
        changed.append("updated state.yaml")

    return {"action": "install", "plan": plan, "changed": changed, "skipped": skipped, "state_path": str(runtime_state_path(runtime_dir))}


def audit_profile(hermes_home: Path, profile: str) -> dict[str, Any]:
    pdir = profile_dir(hermes_home, profile)
    soul = pdir / "SOUL.md"
    cfg = pdir / "config.yaml"
    skill_dst = pdir / "skills" / "mochi-squad"
    issues: list[str] = []
    if not pdir.exists(): issues.append("profile_missing")
    if not soul.exists(): issues.append("soul_missing")
    elif "mochi-squad" not in soul.read_text(errors="ignore"): issues.append("soul_does_not_reference_mochi_squad")
    if not cfg.exists(): issues.append("config_missing")
    if not skill_dst.exists(): issues.append("skill_missing")
    return {
        "exists": pdir.exists(),
        "soul": str(soul),
        "config": str(cfg),
        "skill_installed": skill_dst.exists(),
        "core": profile in CORE_PROFILES,
        "status": "ok" if not issues else ("fail" if "profile_missing" in issues else "warn"),
        "issues": issues,
    }


def verify(hermes_home: Path, runtime_dir: Path, include_optional: bool = False) -> dict[str, Any]:
    checks: list[dict[str, Any]] = []
    def add(name: str, ok: bool, severity: str, detail: str = "") -> None:
        checks.append({"name": name, "ok": ok, "severity": severity, "detail": detail})

    add("runtime_dir", runtime_dir.is_dir(), "fail", str(runtime_dir))
    add("config_yaml", (runtime_dir / "config.yaml").is_file(), "fail", str(runtime_dir / "config.yaml"))
    add("state_yaml", runtime_state_path(runtime_dir).is_file(), "fail", str(runtime_state_path(runtime_dir)))
    add("logs_dir", (runtime_dir / "logs").is_dir(), "warn", str(runtime_dir / "logs"))
    add("cache_dir", (runtime_dir / "cache").is_dir(), "warn", str(runtime_dir / "cache"))
    add("watchdog_script", (runtime_dir / "scripts" / "blocked-watchdog.py").is_file(), "warn", str(runtime_dir / "scripts" / "blocked-watchdog.py"))

    state = read_json_yaml(runtime_state_path(runtime_dir))
    if state.get("_parse_error"):
        add("state_parse", False, "fail", state["_parse_error"])
    elif state:
        add("state_version", state.get("version") == SKILL_VERSION, "warn", str(state.get("version")))

    profiles = list(CORE_PROFILES) + (list(OPTIONAL_PROFILES) if include_optional else [])
    audits = {name: audit_profile(hermes_home, name) for name in profiles}
    for name, audit in audits.items():
        add(f"profile:{name}", audit["status"] == "ok", "fail" if name in CORE_PROFILES else "warn", ",".join(audit["issues"]))

    failed = [c for c in checks if not c["ok"] and c["severity"] == "fail"]
    warned = [c for c in checks if not c["ok"] and c["severity"] == "warn"]
    readiness = "runtime_ready" if not failed and not warned else ("runtime_warn" if not failed else "runtime_not_installed")
    result = {
        "action": "verify",
        "ready": not failed,
        "readiness": readiness,
        "hermes_home": str(hermes_home),
        "runtime_dir": str(runtime_dir),
        "checks": checks,
        "profiles": audits,
        "suggested_action": None,
    }
    if failed:
        result["suggested_action"] = "run setup.py --install or setup.py --repair after reviewing setup.py --plan"
    elif warned:
        result["suggested_action"] = "review warnings; some optional/runtime watcher components may be missing"
    return result


def repair(hermes_home: Path, runtime_dir: Path, include_optional: bool = False) -> dict[str, Any]:
    # Repair is deliberately conservative: same safe creates as install, no overwrites.
    out = install(hermes_home, runtime_dir, include_optional=include_optional)
    out["action"] = "repair"
    out["note"] = "Conservative repair only creates missing generated files/profiles and never overwrites existing SOUL/config files."
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description="Mochi Squad setup/doctor tool")
    parser.add_argument("--hermes-home", default=None, help="Hermes home (default: $HERMES_HOME or ~/.hermes)")
    parser.add_argument("--runtime-dir", default=None, help="Runtime dir (default: $HERMES_HOME/mochi-squad)")
    parser.add_argument("--include-optional", action="store_true", help="Also include optional mochi-research profile")
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--plan", action="store_true", help="Print intended changes without writing files")
    mode.add_argument("--install", action="store_true", help="Create missing runtime/profile files without overwriting")
    mode.add_argument("--verify", action="store_true", help="Run side-effect-free readiness checks")
    mode.add_argument("--repair", action="store_true", help="Conservatively recreate missing generated files")
    args = parser.parse_args()

    hermes_home = default_hermes_home(args.hermes_home)
    runtime_dir = Path(args.runtime_dir).expanduser().resolve() if args.runtime_dir else default_runtime_dir(hermes_home)

    if args.plan:
        out = build_plan(hermes_home, runtime_dir, include_optional=args.include_optional)
    elif args.install:
        out = install(hermes_home, runtime_dir, include_optional=args.include_optional)
    elif args.verify:
        out = verify(hermes_home, runtime_dir, include_optional=args.include_optional)
    elif args.repair:
        out = repair(hermes_home, runtime_dir, include_optional=args.include_optional)
    else:
        parser.print_help()
        return 1

    json.dump(out, sys.stdout, indent=2, sort_keys=True)
    sys.stdout.write("\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
