#!/usr/bin/env python3
"""Mochi Squad minimal idempotent install/verify/repair scaffold.

Usage:
    python setup.py --install          Create local runtime skeleton
    python setup.py --verify           Check local runtime against expected state
    python setup.py --repair           Attempt safe repairs

All operations are idempotent and safe to re-run.
"""

import argparse
import json
import os
import sys

SKILL_VERSION = "0.1.0"

TEMPLATE_CONFIG = """# Mochi Squad local runtime config
# Generated by setup.py --install. Edit for your deployment.

profiles:
  plan: mochi-plan
  exec: mochi-exec
  review: mochi-review
  research: mochi-research

watchers:
  blocked:
    enabled: false
    schedule: "every 5m"
    notify_target: origin

virtual_office:
  enabled: false
"""

TEMPLATE_STATE = {
    "version": SKILL_VERSION,
    "installed": True,
    "last_verified_at": None,
    "readiness": "runtime_ready",
    "blocked_watcher": {
        "installed": False,
        "last_status": "not_configured",
    },
    "virtual_office": {
        "installed": False,
        "reason": "deferred",
    },
    "profiles": {},
}


def default_runtime_dir(hermes_home: str | None = None) -> str:
    """Return the default Mochi Squad runtime directory path."""
    base = hermes_home or os.environ.get(
        "HERMES_HOME",
        os.path.expanduser("~/.hermes"),
    )
    return os.path.join(base, "mochi", "mochi-squad")


def ensure_dir(path: str) -> None:
    """Create directory path if it does not exist."""
    os.makedirs(path, exist_ok=True)


def cmd_install(runtime_dir: str) -> dict:
    """Idempotently create local runtime skeleton."""
    result = {
        "action": "install",
        "target": runtime_dir,
        "created": [],
        "skipped": [],
    }

    ensure_dir(runtime_dir)

    # Config
    config_path = os.path.join(runtime_dir, "config.yaml")
    if os.path.isfile(config_path):
        result["skipped"].append("config.yaml already exists")
    else:
        with open(config_path, "w") as f:
            f.write(TEMPLATE_CONFIG)
        result["created"].append("config.yaml")

    # State
    state_path = os.path.join(runtime_dir, "state.json")
    if os.path.isfile(state_path):
        result["skipped"].append("state.json already exists")
    else:
        state = {**TEMPLATE_STATE, "last_verified_at": None}
        with open(state_path, "w") as f:
            json.dump(state, f, indent=2)
        result["created"].append("state.json")

    # Subdirectories
    for subdir in ("logs", "cache"):
        subpath = os.path.join(runtime_dir, subdir)
        if os.path.isdir(subpath):
            result["skipped"].append(f"{subdir}/ already exists")
        else:
            ensure_dir(subpath)
            result["created"].append(f"{subdir}/")

    return result


def cmd_verify(runtime_dir: str) -> dict:
    """Check local runtime against expected layout."""
    result = {
        "action": "verify",
        "target": runtime_dir,
        "present": [],
        "missing": [],
    }

    expected = [
        ("config.yaml", "file"),
        ("state.json", "file"),
        ("logs", "dir"),
        ("cache", "dir"),
    ]

    for name, kind in expected:
        full_path = os.path.join(runtime_dir, name)
        exists = (kind == "file" and os.path.isfile(full_path)) or (
            kind == "dir" and os.path.isdir(full_path)
        )
        if exists:
            result["present"].append(name)
        else:
            result["missing"].append(name)

    # Parse state.json version if present
    state_path = os.path.join(runtime_dir, "state.json")
    if os.path.isfile(state_path):
        try:
            with open(state_path) as f:
                state = json.load(f)
            state_version = state.get("version")
            if state_version:
                result["state_version"] = state_version
                result["version_match"] = state_version == SKILL_VERSION
            else:
                result["state_version"] = None
                result["version_match"] = False
        except (json.JSONDecodeError, OSError) as exc:
            result["state_error"] = str(exc)

    return result


def cmd_repair(runtime_dir: str) -> dict:
    """Attempt safe repairs on missing runtime components."""
    verify = cmd_verify(runtime_dir)
    result = {
        "action": "repair",
        "target": runtime_dir,
        "repaired": [],
        "unrepairable": [],
    }

    if not verify["missing"]:
        result["repaired"].append("nothing needed")
        return result

    for name in verify["missing"]:
        full_path = os.path.join(runtime_dir, name)
        if name == "config.yaml":
            with open(full_path, "w") as f:
                f.write(TEMPLATE_CONFIG)
            result["repaired"].append("config.yaml")
        elif name == "state.json":
            state = {**TEMPLATE_STATE, "last_verified_at": None}
            with open(full_path, "w") as f:
                json.dump(state, f, indent=2)
            result["repaired"].append("state.json")
        elif name in ("logs", "cache"):
            ensure_dir(full_path)
            result["repaired"].append(f"{name}/")
        else:
            result["unrepairable"].append(
                f"{name}: no automatic repair available"
            )

    return result


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Mochi Squad setup scaffold"
    )
    parser.add_argument(
        "--runtime-dir",
        default=None,
        help="Target runtime directory (default: $HERMES_HOME/mochi/mochi-squad)",
    )
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--install", action="store_true", help="Create runtime skeleton")
    mode.add_argument("--verify", action="store_true", help="Check runtime status")
    mode.add_argument("--repair", action="store_true", help="Attempt safe repairs")

    args = parser.parse_args()
    runtime_dir = args.runtime_dir or default_runtime_dir()

    if args.install:
        out = cmd_install(runtime_dir)
    elif args.verify:
        out = cmd_verify(runtime_dir)
    elif args.repair:
        out = cmd_repair(runtime_dir)
    else:
        parser.print_help()
        return 1

    json.dump(out, sys.stdout, indent=2)
    sys.stdout.write("\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())