#!/usr/bin/env python3
"""Deterministic Mochi Squad setup / verify / repair tool."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

SKILL_VERSION = "0.1.0"
CORE_PROFILES = ("mochi-exec", "mochi-review")
PROFILE_TOOLSETS = {
    "mochi-exec": ["file", "terminal", "kanban", "skills"],
    "mochi-review": ["file", "terminal", "browser", "kanban", "skills"],
}
PROFILE_SKILLS = {name: ["mochi-squad"] for name in CORE_PROFILES}
PROFILE_DISALLOWED_TOOLSETS = {
    "mochi-exec": ["discord_admin"],
    "mochi-review": ["discord_admin", "cronjob"],
}
CRON_SCRIPT_NAME = "mochi-squad-blocked-watchdog.py"
CRON_JOB_NAME = "Mochi Squad blocked watchdog"

TEMPLATE_CONFIG = """# Mochi Squad local runtime config
# Generated by setup.py --install. Edit for your deployment.

kanban:
  db_path: auto

watchers:
  blocked:
    enabled: false
    schedule: "every 5m"
    notify_target: origin
    script: mochi-squad-blocked-watchdog.py

virtual_office:
  enabled: false
  listen_host: 127.0.0.1
  port: 3000
  public_base_url: null
"""


def now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def package_root() -> Path:
    return Path(__file__).resolve().parents[1]


def default_hermes_home(value: str | None = None) -> Path:
    return Path(value or os.environ.get("HERMES_HOME", os.path.expanduser("~/.hermes"))).expanduser().resolve()


def default_runtime_dir(hermes_home: Path) -> Path:
    return hermes_home / "mochi-squad"


def profile_dir(hermes_home: Path, profile: str) -> Path:
    return hermes_home / "profiles" / profile


def state_path(runtime_dir: Path) -> Path:
    return runtime_dir / "state.yaml"


def read_json_yaml(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text())
    except json.JSONDecodeError:
        return {"_parse_error": f"{path.name} is expected to be JSON-compatible YAML"}


def write_json_yaml(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n")


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def copy_tree_missing(src: Path, dst: Path) -> bool:
    if dst.exists():
        return False
    ignore = shutil.ignore_patterns(".git", "__pycache__", "*.pyc", ".pytest_cache", "mochi-squad", "logs", "cache")
    shutil.copytree(src, dst, ignore=ignore)
    return True


def recommended_profile_config(profile: str) -> str:
    return """# Mochi Squad recommended Hermes profile config
# Generated only for newly-created profiles. Existing profile configs are audited, not overwritten.

skills:
""" + "".join(f"  - {item}\n" for item in PROFILE_SKILLS[profile]) + "\nenabled_toolsets:\n" + "".join(f"  - {tool}\n" for tool in PROFILE_TOOLSETS[profile])


def profile_template(profile: str) -> Path:
    return package_root() / "templates" / "profiles" / profile / "SOUL.md"


def parse_yaml_list(text: str, key: str) -> list[str] | None:
    """Tiny parser for simple top-level YAML lists used in profile configs."""
    lines = text.splitlines()
    result: list[str] = []
    in_key = False
    found = False
    for line in lines:
        raw = line.rstrip()
        stripped = raw.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if not raw.startswith(" ") and stripped.endswith(":"):
            current = stripped[:-1]
            if current == key:
                in_key = True
                found = True
                result = []
                continue
            if in_key:
                break
        elif in_key:
            if stripped.startswith("-"):
                value = stripped[1:].strip().strip('"\'')
                if value:
                    result.append(value)
            elif not raw.startswith(" "):
                break
    return result if found else None


def profile_config_lists(path: Path) -> dict[str, list[str] | None]:
    if not path.exists():
        return {"skills": None, "enabled_toolsets": None}
    text = path.read_text(errors="ignore")
    toolsets = parse_yaml_list(text, "enabled_toolsets")
    if toolsets is None:
        toolsets = parse_yaml_list(text, "toolsets")
    return {"skills": parse_yaml_list(text, "skills"), "enabled_toolsets": toolsets}


def audit_profile(hermes_home: Path, profile: str) -> dict[str, Any]:
    pdir = profile_dir(hermes_home, profile)
    soul = pdir / "SOUL.md"
    cfg = pdir / "config.yaml"
    skill_dst = pdir / "skills" / "mochi-squad"
    issues: list[str] = []
    warnings: list[str] = []
    proposed: dict[str, list[str]] = {}

    if not pdir.exists():
        issues.append("profile_missing")
    if not soul.exists():
        issues.append("soul_missing")
    elif "mochi-squad" not in soul.read_text(errors="ignore"):
        warnings.append("soul_does_not_reference_mochi_squad")
    if not cfg.exists():
        warnings.append("config_missing_uses_global_defaults")
        current_skills = None
        current_toolsets = None
    else:
        lists = profile_config_lists(cfg)
        current_skills = lists["skills"]
        current_toolsets = lists["enabled_toolsets"]
        missing_skills = [s for s in PROFILE_SKILLS[profile] if s not in (current_skills or [])]
        missing_toolsets = [t for t in PROFILE_TOOLSETS[profile] if t not in (current_toolsets or [])]
        disallowed_toolsets = [t for t in PROFILE_DISALLOWED_TOOLSETS.get(profile, []) if t in (current_toolsets or [])]
        if missing_skills:
            warnings.append("missing_required_skills")
            proposed["skills"] = missing_skills
        if missing_toolsets:
            warnings.append("missing_required_toolsets")
            proposed["enabled_toolsets"] = missing_toolsets
        if disallowed_toolsets:
            warnings.append("disallowed_toolsets_present")
            proposed["remove_enabled_toolsets"] = disallowed_toolsets

    if not skill_dst.exists():
        issues.append("skill_missing")

    status = "ok"
    if issues:
        status = "fail" if "profile_missing" in issues or "skill_missing" in issues else "warn"
    elif warnings:
        status = "warn"

    return {
        "exists": pdir.exists(),
        "soul": str(soul),
        "config": str(cfg),
        "skill_installed": skill_dst.exists(),
        "core": profile in CORE_PROFILES,
        "required_skills": PROFILE_SKILLS[profile],
        "required_toolsets": PROFILE_TOOLSETS[profile],
        "current_skills": current_skills if cfg.exists() else None,
        "current_toolsets": current_toolsets if cfg.exists() else None,
        "status": status,
        "issues": issues,
        "warnings": warnings,
        "proposed_additions": proposed,
    }


def cron_jobs_path(hermes_home: Path) -> Path:
    return hermes_home / "cron" / "jobs.json"


def load_jobs(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {"jobs": []}
    return json.loads(path.read_text())


def cron_job_id(hermes_home: Path) -> str:
    return hashlib.sha256(f"{hermes_home}:mochi-squad-blocked-watchdog".encode()).hexdigest()[:12]


def install_cron_job(hermes_home: Path, runtime_dir: Path, deliver: str = "origin") -> dict[str, Any]:
    scripts_dir = hermes_home / "scripts"
    scripts_dir.mkdir(parents=True, exist_ok=True)
    src = package_root() / "scripts" / "blocked-watchdog.py"
    dst = scripts_dir / CRON_SCRIPT_NAME
    shutil.copy2(src, dst)

    jobs_path = cron_jobs_path(hermes_home)
    jobs_path.parent.mkdir(parents=True, exist_ok=True)
    data = load_jobs(jobs_path)
    jobs = data.setdefault("jobs", [])
    jid = cron_job_id(hermes_home)
    job = {
        "id": jid,
        "name": CRON_JOB_NAME,
        "prompt": "",
        "skills": [],
        "skill": None,
        "model": None,
        "provider": None,
        "base_url": None,
        "script": CRON_SCRIPT_NAME,
        "no_agent": True,
        "context_from": None,
        "schedule": {"kind": "interval", "minutes": 5, "display": "every 5m"},
        "schedule_display": "every 5m",
        "repeat": {"times": None, "completed": 0},
        "enabled": True,
        "state": "scheduled",
        "paused_at": None,
        "paused_reason": None,
        "created_at": now_iso(),
        "next_run_at": None,
        "last_run_at": None,
        "last_status": None,
        "last_error": None,
        "last_delivery_error": None,
        "deliver": deliver,
        "origin": None,
        "enabled_toolsets": None,
        "workdir": None,
    }
    replaced = False
    for idx, existing in enumerate(jobs):
        if existing.get("id") == jid or existing.get("name") == CRON_JOB_NAME:
            # Preserve run counters and timestamps where possible.
            job["created_at"] = existing.get("created_at") or job["created_at"]
            job["repeat"] = existing.get("repeat") or job["repeat"]
            job["last_run_at"] = existing.get("last_run_at")
            job["last_status"] = existing.get("last_status")
            job["last_error"] = existing.get("last_error")
            job["last_delivery_error"] = existing.get("last_delivery_error")
            jobs[idx] = job
            replaced = True
            break
    if not replaced:
        jobs.append(job)
    jobs_path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n")
    return {"job_id": jid, "jobs_path": str(jobs_path), "script": str(dst), "created_or_updated": True, "replaced": replaced}


def build_plan(hermes_home: Path, runtime_dir: Path, install_cron: bool = False, deliver: str = "origin") -> dict[str, Any]:
    actions: list[dict[str, str]] = []
    warnings: list[str] = []
    for directory in (runtime_dir, runtime_dir / "logs", runtime_dir / "cache", runtime_dir / "scripts"):
        if not directory.exists():
            actions.append({"action": "create_dir", "path": str(directory)})
    for filename in ("config.yaml", "state.yaml"):
        if not (runtime_dir / filename).exists():
            actions.append({"action": "create_file", "path": str(runtime_dir / filename)})
    if not (runtime_dir / "scripts" / "blocked-watchdog.py").exists():
        actions.append({"action": "copy_file", "path": str(runtime_dir / "scripts" / "blocked-watchdog.py")})
    if install_cron:
        actions.append({"action": "copy_cron_script", "path": str(hermes_home / "scripts" / CRON_SCRIPT_NAME)})
        actions.append({"action": "create_or_update_cron_job", "path": str(cron_jobs_path(hermes_home))})

    for name in CORE_PROFILES:
        pdir = profile_dir(hermes_home, name)
        if not pdir.exists():
            actions.append({"action": "create_profile", "path": str(pdir)})
            actions.append({"action": "copy_profile_soul", "path": str(pdir / "SOUL.md")})
            actions.append({"action": "write_profile_config", "path": str(pdir / "config.yaml")})
        else:
            audit = audit_profile(hermes_home, name)
            if audit["status"] != "ok":
                warnings.append(f"{name}: {audit['issues'] + audit['warnings']} proposed={audit['proposed_additions']}")
        if not (pdir / "skills" / "mochi-squad").exists():
            actions.append({"action": "install_profile_skill", "path": str(pdir / "skills" / "mochi-squad")})

    return {
        "action": "plan",
        "hermes_home": str(hermes_home),
        "runtime_dir": str(runtime_dir),
        "core_profiles": list(CORE_PROFILES),
        "will_change": actions,
        "warnings": warnings,
        "approval_required": [
            "editing existing profile SOUL.md or config.yaml",
            "choosing deployment-specific model/provider IDs",
            "configuring DNS, Cloudflare, reverse proxies, public URLs, or production services",
            "making repositories public or merging pull requests",
        ],
        "cron_install_requested": install_cron,
        "cron_deliver": deliver if install_cron else None,
    }


def install(hermes_home: Path, runtime_dir: Path, install_cron_flag: bool = False, deliver: str = "origin") -> dict[str, Any]:
    changed: list[str] = []
    skipped: list[str] = []
    runtime_dir.mkdir(parents=True, exist_ok=True)
    for sub in ("logs", "cache", "scripts"):
        d = runtime_dir / sub
        if d.exists(): skipped.append(f"{sub}/ already exists")
        else:
            d.mkdir(parents=True); changed.append(f"created {sub}/")
    cfg = runtime_dir / "config.yaml"
    if cfg.exists(): skipped.append("config.yaml already exists")
    else:
        cfg.write_text(TEMPLATE_CONFIG); changed.append("created config.yaml")
    watcher_src = package_root() / "scripts" / "blocked-watchdog.py"
    watcher_dst = runtime_dir / "scripts" / "blocked-watchdog.py"
    if watcher_dst.exists(): skipped.append("scripts/blocked-watchdog.py already exists")
    else:
        shutil.copy2(watcher_src, watcher_dst); changed.append("copied scripts/blocked-watchdog.py")

    profile_audits: dict[str, Any] = {}
    for name in CORE_PROFILES:
        pdir = profile_dir(hermes_home, name)
        existed = pdir.exists()
        pdir.mkdir(parents=True, exist_ok=True)
        if not existed: changed.append(f"created profile {name}")
        soul = pdir / "SOUL.md"
        if not existed and profile_template(name).exists():
            shutil.copy2(profile_template(name), soul); changed.append(f"copied {name}/SOUL.md")
        elif soul.exists(): skipped.append(f"{name}/SOUL.md exists")
        else: skipped.append(f"{name}/SOUL.md missing; existing profile not modified")
        pcfg = pdir / "config.yaml"
        if not existed:
            pcfg.write_text(recommended_profile_config(name)); changed.append(f"wrote {name}/config.yaml")
        elif pcfg.exists(): skipped.append(f"{name}/config.yaml exists")
        else: skipped.append(f"{name}/config.yaml missing; existing profile not modified")
        skill_dst = pdir / "skills" / "mochi-squad"
        if copy_tree_missing(package_root(), skill_dst): changed.append(f"installed mochi-squad skill for {name}")
        else: skipped.append(f"{name}/skills/mochi-squad exists")
        profile_audits[name] = audit_profile(hermes_home, name)

    cron_result = None
    if install_cron_flag:
        cron_result = install_cron_job(hermes_home, runtime_dir, deliver=deliver)
        changed.append("created_or_updated cron job")

    st = read_json_yaml(state_path(runtime_dir))
    st.update({
        "version": SKILL_VERSION,
        "installed": True,
        "installed_at": st.get("installed_at") or now_iso(),
        "last_verified_at": now_iso(),
        "runtime_dir": str(runtime_dir),
        "profiles": profile_audits,
        "scripts": {
            "blocked-watchdog.py": {"installed": watcher_dst.exists(), "path": str(watcher_dst), "sha256": sha256(watcher_dst)},
            CRON_SCRIPT_NAME: {"installed": (hermes_home / "scripts" / CRON_SCRIPT_NAME).exists(), "path": str(hermes_home / "scripts" / CRON_SCRIPT_NAME)},
        },
        "blocked_watcher": {
            "cron_installed": bool(cron_result),
            "cron_job_id": cron_result["job_id"] if cron_result else st.get("blocked_watcher", {}).get("cron_job_id"),
            "dedupe_state_path": str(runtime_dir / "blocked-watchdog-state.json"),
        },
        "virtual_office": {"enabled": False, "reason": "deferred"},
    })
    write_json_yaml(state_path(runtime_dir), st)
    changed.append("updated state.yaml")
    return {"action": "install", "changed": changed, "skipped": skipped, "state_path": str(state_path(runtime_dir)), "cron": cron_result}


def verify(hermes_home: Path, runtime_dir: Path) -> dict[str, Any]:
    checks: list[dict[str, Any]] = []
    def add(name: str, ok: bool, severity: str, detail: Any = "") -> None:
        checks.append({"name": name, "ok": ok, "severity": severity, "detail": detail})
    add("runtime_dir", runtime_dir.is_dir(), "fail", str(runtime_dir))
    add("config_yaml", (runtime_dir / "config.yaml").is_file(), "fail", str(runtime_dir / "config.yaml"))
    st = read_json_yaml(state_path(runtime_dir))
    add("state_yaml", state_path(runtime_dir).is_file() and not st.get("_parse_error"), "fail", str(state_path(runtime_dir)))
    if st and not st.get("_parse_error"):
        add("state_version", st.get("version") == SKILL_VERSION, "warn", st.get("version"))
    add("logs_dir", (runtime_dir / "logs").is_dir(), "warn", str(runtime_dir / "logs"))
    add("cache_dir", (runtime_dir / "cache").is_dir(), "warn", str(runtime_dir / "cache"))
    add("watchdog_script", (runtime_dir / "scripts" / "blocked-watchdog.py").is_file(), "warn", str(runtime_dir / "scripts" / "blocked-watchdog.py"))
    profiles = {name: audit_profile(hermes_home, name) for name in CORE_PROFILES}
    for name, audit in profiles.items():
        add(f"profile:{name}", audit["status"] == "ok", "fail" if audit["issues"] else "warn", audit)
    cron = None
    jobs_path = cron_jobs_path(hermes_home)
    if jobs_path.exists():
        try:
            jobs = load_jobs(jobs_path).get("jobs", [])
            cron = next((j for j in jobs if j.get("id") == cron_job_id(hermes_home) or j.get("name") == CRON_JOB_NAME), None)
        except Exception as exc:
            cron = {"error": str(exc)}
    add("cron_job", cron is not None, "warn", cron or "not installed")
    failed = [c for c in checks if not c["ok"] and c["severity"] == "fail"]
    warned = [c for c in checks if not c["ok"] and c["severity"] == "warn"]
    return {
        "action": "verify",
        "ready": not failed,
        "readiness": "runtime_ready" if not failed and not warned else ("runtime_warn" if not failed else "runtime_not_installed"),
        "hermes_home": str(hermes_home),
        "runtime_dir": str(runtime_dir),
        "checks": checks,
        "profiles": profiles,
        "cron": cron,
        "suggested_action": None if not failed and not warned else "review warnings/failures; run setup.py --plan then --install/--repair as appropriate",
    }


def repair(hermes_home: Path, runtime_dir: Path, install_cron_flag: bool = False, deliver: str = "origin") -> dict[str, Any]:
    out = install(hermes_home, runtime_dir, install_cron_flag=install_cron_flag, deliver=deliver)
    out["action"] = "repair"
    out["note"] = "Conservative repair creates missing generated files/profiles and never overwrites existing SOUL/config files."
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description="Mochi Squad setup/doctor tool")
    parser.add_argument("--hermes-home", default=None)
    parser.add_argument("--runtime-dir", default=None)
    parser.add_argument("--install-cron", action="store_true", help="Explicitly create/update no-agent blocked watcher cron job")
    parser.add_argument("--deliver", default="origin", help="Cron delivery target when --install-cron is used")
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--plan", action="store_true")
    mode.add_argument("--install", action="store_true")
    mode.add_argument("--verify", action="store_true")
    mode.add_argument("--repair", action="store_true")
    args = parser.parse_args()
    hermes_home = default_hermes_home(args.hermes_home)
    runtime_dir = Path(args.runtime_dir).expanduser().resolve() if args.runtime_dir else default_runtime_dir(hermes_home)
    if args.plan:
        out = build_plan(hermes_home, runtime_dir, install_cron=args.install_cron, deliver=args.deliver)
    elif args.install:
        out = install(hermes_home, runtime_dir, install_cron_flag=args.install_cron, deliver=args.deliver)
    elif args.verify:
        out = verify(hermes_home, runtime_dir)
    elif args.repair:
        out = repair(hermes_home, runtime_dir, install_cron_flag=args.install_cron, deliver=args.deliver)
    else:
        parser.print_help(); return 1
    json.dump(out, sys.stdout, indent=2, sort_keys=True)
    sys.stdout.write("\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
